### ISSUE TITLE
I was able to make a vmf and tried opening it in hammer but it requires too many blocks with error BlockArray<?, 6, 68> - too many blocks needed

### ISSUE THREAD

**Issue by kurti256** [snake-biscuits/vmf_tool#10]

**Comment by snake-biscuits** [comment]
it's possible you have a model in there that's too complex to work as a brush
If I had the .obj & .vmf file you're working with I could tell you more

**Comment by kurti256** [comment]
> 
> 
> it's possible you have a model in there that's too complex to work as a brush
> If I had the .obj & .vmf file you're working with I could tell you more


[minecraft to tf2 map.zip](https://github.com/snake-biscuits/vmf_tool/files/4925153/minecraft.to.tf2.map.zip)
I hope this helps

**Comment by snake-biscuits** [comment]
Ah, a minecraft map, I'm surprised someone hasn't tried to use this tool for that already.
The error is coming from the everything being one model, and having multiple co-planar faces
A lot needs to be done to the `.obj` to make it convert into a `.vmf` well

I'm prepared to make some tools to make it easier to turn minecraft maps in this .obj form into vmfs, **but not for free.**

If you don't want to have to pay for that, I'll probably still try to make those tools, but much slower.
I can also guide you through some of the manual work required. For example:
-  You'd have to split all the textures into their own file.
-  Split all the geometry in the .obj by material.
-  Reshape everything to look like valid solids to hammer (simplifying as you go)...  

There's a lot of manual work required from this point.

You can contact me on Discord to talk about how you want to proceed here: `b!scuit#3659`

**Comment by kurti256** [comment]
> 
> 
> Ah, a minecraft map, I'm surprised someone hasn't tried to use this tool for that already.
> The error is coming from the everything being one model, and having multiple co-planar faces
> A lot needs to be done to the `.obj` to make it convert into a `.vmf` well
> 
> I'm prepared to make some tools to make it easier to turn minecraft maps in this .obj form into vmfs, **but not for free.**
> 
> If you don't want to have to pay for that, I'll probably still try to make those tools, but much slower.
> I can also guide you through some of the manual work required. For example:
> 
>     * You'd have to split all the textures into their own file.
> 
>     * Split all the geometry in the .obj by material.
> 
>     * Reshape everything to look like valid solids to hammer (simplifying as you go)...
> 
> 
> There's a lot of manual work required from this point.
> 
> You can contact me on Discord to talk about how you want to proceed here: `b!scuit#3659`

I sent a friend request I'm currently 17 and don't have control over my money yet but i'd be more then happy to help whether that means learning to code or whatever it entails i'm happy to help
