### ISSUE TITLE
I tried using it and it said: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: malformed \N character escape

### ISSUE THREAD

**Issue by kurti256** [snake-biscuits/vmf_tool#8]
for filepath in sys.argv[1:]:
        base.world.solids = obj_solids("E:\New pc files\vmf_tool-master\tf2")
        with open("E:\New pc files\vmf_tool-master\tf2" + ".vmf", "w") as out_file:
            vmf_tool.export(base, out_file)

This is what I changed it to at the bottom

It also highlighted the ( from with open("E:\New pc files\vmf_tool-master\tf2" + ".vmf", "w") as out_file:

**Comment by snake-biscuits** [comment]
are you trying to turn a vmf file into an obj file?

**Comment by snake-biscuits** [comment]
also, you shouldn't have to modify the script to get it to work, did you try dragging an .obj over the script before trying this?

**Comment by snake-biscuits** [comment]
the error is from using the "\" character in the filename `"E:\New pc files\vmf_tool-master\tf2"`
if you use `"E:/New pc files/vmf_tool-master/tf2"` instead, it should work

**Comment by kurti256** [comment]
> 
> 
> the error is from using the `\` character in the filename `"E:\New pc files\vmf_tool-master\tf2"`
> if you use `"E:/New pc files/vmf_tool-master/tf2"` instead, it should work

thank you this worked sorry for the issues
