### ISSUE TITLE
  File "E:\vmf_tool-master\vmf_tool.py", line 53, in <module>     base = vmf_tool.parse_lines(base_file.readlines()) AttributeError: module 'vmf_tool' has no attribute 'parse_lines'

### ISSUE THREAD

**Issue by kurti256** [snake-biscuits/vmf_tool#9]

**Comment by snake-biscuits** [comment]
you probably don't have the latest version of vmf_tool, did you clone the latest version of the whole thing or just grab the latest version of the obj converter? you need the latest copy of both for it to work

**Comment by kurti256** [comment]
> 
> 
> you probably don't have the latest version of vmf_tool, did you clone the latest version of the whole thing or just grab the latest version of the obj converter? you need the latest copy of both for it to work

Thank you that works and I was able to make a vmf and tried opening it in hammer but apparently it requires too many blocks with <?, 6, 68>
